default:
  image: 'ubuntu:23.10'

stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - apt update
    - apt install npm -y
    - npm install
    - np install @angular/cli
    - ng build
    - echo "Compile complete."
  artifacts:
    paths:
      - dist

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
