name: build-and-deploy
run-name: ${{ github.actor }} is deploying shopping-list
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g @angular/cli
      - run: npm install
      - run: ng build
      - run: ls dist
      - name: deploy
        env:
          ssh_key: ${{ secrets.SSH_KEY }}
        run: |
          echo "$ssh_key" > ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa
          scp -r -i ~/.ssh/id_rsa dist/shopping-list marcin@marczyk.synology.me:/volume1/www/test