name: build-and-deploy
run-name: ${{ github.actor }} is deploying shopping-list
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g @angular/cli
      - run: npm install
      - run: ng build
      - run: ls dist
      - name: deploy
        run: |
          scp -P 2222 -r -i ~/.ssh/id_rsa dist/shopping-list/* marcin@marczyk.synology.me:/volume1/www/shopping-list
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/marczykm/shopping-list
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/marczykm/shopping-list:latest
          labels: ${{ steps.meta.outputs.labels }}
